import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Theme // Change",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    //  ///`//suppresshydration warning theme change...........................................

    // npm install next-themes
    // npm install react-icons

    // npx shadcn@latest init
    // npx shadcn@latest add button

    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" enableSystem defaultTheme="system" >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
